apiVersion: v1
kind: Service
metadata:
  name: fcs-web-service
  namespace: fcs
spec:
  type: NodePort
  selector:
    app: fcs-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090